export { runQuery, apiUrl, runWithLimit, runWithLimitSettled, SEARCH_FANOUT_LIMIT, type RunWithLimitOptions } from './search.js';
export {
  runSearchJob,
  SearchJobError,
  type SearchFailureKind,
  type SearchHttpClient,
  type SearchJobOptions,
} from './search-job.js';
export {
  ANY_DATASET,
  KqlSafetyError,
  assertKqlPredicate,
  assertReadOnlyKql,
  kqlBracketField,
  kqlDatasetId,
  kqlFieldKey,
  kqlFiniteNumber,
  kqlInteger,
  kqlStringLiteral,
  kqlTime,
} from './kql.js';
export {
  ResilienceBoundary,
  type ResilienceBoundaryProps,
  type ResilienceFallbackProps,
} from './ResilienceBoundary.js';
export {
  getBearerToken,
  fetchBearerToken,
  getCachedBearerToken,
  clearBearerTokenCache,
  oauthEndpoints,
  type OAuthConfig,
  type BearerToken,
  type CachedBearerTokenOptions,
} from './auth.js';
export {
  KvError,
  kvGetJson,
  kvGetText,
  kvPutJson,
  kvPutText,
  memberKey,
  parseMemberKey,
  type KvResult,
} from './kv.js';
export {
  loadSettings,
  saveSettings,
  saveSettingsResult,
  DEFAULT_SETTINGS_KEY,
  type AppSettings,
  type SettingsKeyOptions,
  type SaveSettingsOptions,
} from './settings.js';
export { loadDotEnv } from './dotenv.js';
export {
  reconcile,
  planOnly,
  unprovisionAll,
  listProvisioned,
  diffProvisioned,
  applyProvisioningPlan,
  savedSearchesPath,
  createBrowserHttpClient,
  createNodeHttpClient,
  type ProvisionedSearch,
  type ProvisionerConfig,
  type SeedLookup,
  type SavedSearchRow,
  type PlanAction,
  type ActionResult,
  type HttpClient,
  applyProvisioningActions,
  validateProvisionerPlan,
  type NotificationResult,
  type NotificationTargetResult,
  type ProvisionPlanValidator,
} from './provisioner.js';
export {
  validateProvisionPlan,
  validateProvisionQuery,
  validateSavedSearchName,
  ProvisionPlanError,
  SAVED_SEARCH_NAME_PATTERN,
  type ProvisionRule,
  type ProvisionProblemRule,
  type ProvisionProblem,
  type ProvisionValidation,
  type ValidateProvisionPlanOptions,
} from './provision-guard.js';
export {
  runProvisionCanary,
  type ProvisionCanaryOptions,
  type ProvisionCanaryReport,
  type ProvisionCanaryProbe,
  type ProvisionCanaryLookupProbe,
  type ProvisionProbeContext,
  type ProvisionProbeResult,
} from './provision-canary.js';
export {
  DEFAULT_NOTIFICATION_GROUP,
  notificationsPath,
  notificationTargetsPath,
  savedSearchNotificationId,
  savedSearchNotificationBody,
  ensureNotificationTarget,
  ensureSavedSearchNotification,
  removeSavedSearchNotification,
  removeNotificationsForSearch,
  type NotificationTarget,
  type SavedSearchNotification,
  type SavedSearchNotificationConf,
} from './notifications.js';
export {
  readVtResults,
  latestRunRows,
  runStartedMs,
  vtResultsQuery,
  DEFAULT_VT_RESULTS_LIMIT,
  type ReadVtResultsOptions,
  type VtRunQuery,
} from './vt-results.js';
export {
  CADENCE_OPTIONS,
  DEFAULT_CADENCE,
  cadenceToCron,
  offsetCron,
  getSearchCadence,
  getSearchCadenceCron,
  setSearchCadence,
  subscribeSearchCadence,
  type CadenceOption,
  type CadenceChoice,
} from './cadence.js';
export {
  getCurrentDataset,
  setCurrentDataset,
  subscribeDataset,
  useDataset,
  getDatasetLoadError,
  setDatasetLoadError,
  subscribeDatasetLoadError,
  useDatasetLoadError,
} from './dataset.js';
export { DatasetProvider, type DatasetProviderProps } from './DatasetProvider.js';
export {
  Banner,
  useProvisioningBanners,
  collectProvisioningBanners,
  type ProvisioningBannerSpec,
  type ProvisioningBannerSource,
} from './ProvisioningBanner.js';
export {
  DEFAULT_SEARCH_GROUP,
  datasetPath,
  rulesetPath,
  getAcceleratedFieldsStatus,
  ensureAcceleratedFields,
  getRulesetRuleStatus,
  ensureRulesetRule,
  type AcceleratedField,
  type AcceleratedFieldsStatus,
  type AcceleratedFieldsResult,
  type DatasetRule,
  type RulesetRuleStatus,
  type RulesetRuleResult,
  type RuleValidator,
} from './dataset-provisioner.js';
export {
  METRICS_DATASET,
  runMetricsQuery,
  queryRange,
  queryInstant,
  runMetricsDiscovery,
  listMetricMetadata,
  listLabels,
  listSeries,
  listSearchDatasets,
  cachedQueryInstant,
  cachedQueryRange,
  clearMetricsCache,
  type MetricsQueryOptions,
  type MetricSample,
  type MetricSeries,
  type MetricMetadata,
  type MetricsDiscoveryResult,
  type SearchDatasetInfo,
} from './metrics.js';
export {
  browserMetricsCatalog,
  createMetricsCatalog,
  type CatalogTransport,
  type CatalogMetadata,
  type CatalogMetricLabel,
  type CatalogMetricRow,
  type CatalogTotals,
  type LocalSearchEngine,
  type MetricsCatalog,
  type MetricsCatalogConfig,
} from './metrics-catalog.js';
export {
  newQueryGeneration,
  currentQuerySignal,
  withGenerationSignal,
  captureQueryGeneration,
} from './query-generation.js';
export { createStore, useStore, type Store } from './store.js';
export {
  TIME_RANGES,
  binSecondsFor,
  previousWindow,
  relativeTimeMs,
  type TimeRangeOption,
} from './time.js';
export {
  usePageLoad,
  createPageLoadController,
  INITIAL_PAGE_LOAD_STATE,
  type PageLoad,
  type PageLoadContext,
  type PageLoadController,
  type PageLoadFn,
  type PageLoadOptions,
  type PageLoadPhase,
  type PageLoadState,
} from './page-load.js';
export {
  DEFAULT_BACKFILL_WINDOW_SECONDS,
  MIN_BACKFILL_CHUNK_SECONDS,
  SAFE_MAX_EXPORT_EVENTS,
  coverageProbeQuery,
  createMetricsCoverageProbe,
  floorToMinute,
  isRetryableDrop,
  planDensityWindows,
  planFixedWindows,
  readExportStats,
  runMetricsBackfill,
  runMetricsExport,
  splitCoverageSec,
  type BackfillWindow,
  type CoverageSplit,
  type EmitterBackfillResult,
  type ExportStats,
  type MetricsBackfillDeps,
  type MetricsBackfillEmitter,
  type MetricsBackfillOptions,
  type MetricsBackfillProgress,
  type MetricsBackfillResult,
  type MetricsCoverageProbeOptions,
  type RunMetricsExportOptions,
} from './metrics-backfill.js';
export {
  STORED_DATATYPE_EXPR,
  defineGeneratedEvents,
  eventIdExpr,
  exportToSearchClause,
  runGeneratedEventCanary,
  storedDatatypePredicate,
  type CanaryFieldValue,
  type CanaryQueryRunner,
  type CanaryVerdict,
  type GeneratedEventCanaryOptions,
  type GeneratedEvents,
  type GeneratedEventsConfig,
} from './generated-events.js';
export {
  ALERT_STATUSES,
  DEFAULT_ALERT_DEBOUNCE,
  alertCaseKql,
  alertStateKql,
  alertTransitionKql,
  nextAlertCounters,
  nextAlertState,
  type AlertDebounce,
  type AlertKqlFields,
  type AlertKqlOptions,
  type AlertStateInput,
  type AlertStateResult,
  type AlertStatus,
  type AlertTransition,
} from './alert-state.js';
